dist: trusty
env:
  - IMAGE_TAG=latest CONTEXT=./8.0/fpm/
  - IMAGE_TAG=8.0-fpm CONTEXT=./8.0/fpm/
  - IMAGE_TAG=8.0-fpm-dev CONTEXT=./8.0/fpm/dev/
  - IMAGE_TAG=8.0-apache CONTEXT=./8.0/apache/
  - IMAGE_TAG=8.0-apache-dev CONTEXT=./8.0/apache/dev/

  - IMAGE_TAG=7.4-fpm CONTEXT=./7.4/fpm/
  - IMAGE_TAG=7.4-fpm-dev CONTEXT=./7.4/fpm/dev/
  - IMAGE_TAG=7.4-apache CONTEXT=./7.4/apache/
  - IMAGE_TAG=7.4-apache-dev CONTEXT=./7.4/apache/dev/

  - IMAGE_TAG=7.3-fpm CONTEXT=./7.3/fpm/
  - IMAGE_TAG=7.3-fpm-dev CONTEXT=./7.3/fpm/dev/
  - IMAGE_TAG=7.3-apache CONTEXT=./7.3/apache/
  - IMAGE_TAG=7.3-apache-dev CONTEXT=./7.3/apache/dev/

  - IMAGE_TAG=7.2-fpm CONTEXT=./7.2/fpm/
  - IMAGE_TAG=7.2-fpm-dev CONTEXT=./7.2/fpm/dev/
  - IMAGE_TAG=7.2-apache CONTEXT=./7.2/apache/
  - IMAGE_TAG=7.2-apache-dev CONTEXT=./7.2/apache/dev/

  - IMAGE_TAG=7.1-fpm CONTEXT=./7.1/fpm/
  - IMAGE_TAG=7.1-fpm-dev CONTEXT=./7.1/fpm/dev/

  - IMAGE_TAG=7.0-fpm CONTEXT=./7.0/fpm/
  - IMAGE_TAG=7.0-fpm-dev CONTEXT=./7.0/fpm/dev/

  - IMAGE_TAG=5.6-fpm CONTEXT=./5.6/fpm/
  - IMAGE_TAG=5.6-fpm-dev CONTEXT=./5.6/fpm/dev/
  - IMAGE_TAG=5.6-apache CONTEXT=./5.6/apache/
  - IMAGE_TAG=5.6-apache-dev CONTEXT=./5.6/apache/dev/

#  - IMAGE_TAG=5.5-fpm CONTEXT=./5.5/fpm/
#  - IMAGE_TAG=5.5-fpm-dev CONTEXT=./5.5/fpm/dev/
  - IMAGE_TAG=5.5-apache CONTEXT=./5.5/apache/
  - IMAGE_TAG=5.5-apache-dev CONTEXT=./5.5/apache/dev/

  - IMAGE_TAG=5.3-apache CONTEXT=./5.3/apache/
  - IMAGE_TAG=5.3-apache-dev CONTEXT=./5.3/apache/dev/

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - IMAGE="${DOCKER_ACCOUNT}/php:${IMAGE_TAG}"
  - docker build -t $IMAGE $CONTEXT
  - docker images
  - docker push $IMAGE
